# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

PROJECT_DIRECTORY = File.expand_path("..", Dir.pwd)

default_platform(:android)

platform :android do
  desc "Android: Build a new version"
  lane :build do
    Dir.chdir("..") do
      sh("npx react-native-version --increment-build --target android")
    end
    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "android",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => File.join(PROJECT_DIRECTORY, "/fastlane/release.keystore"),
        "android.injected.signing.store.password" => ENV["ANDROID_RELEASE_KEY_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_RELEASE_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_RELEASE_KEY_PASSWORD"],
      }
    )
  end
  
  lane :upload_build_to_diawi do
    diawi(
      token: ENV["DIAWI_TOKEN"],
      file: File.join(PROJECT_DIRECTORY, "android/app/build/outputs/apk/release/app-release.apk"),
    )

    result_url = lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI]

    path = PROJECT_DIRECTORY + "/android/app/build.gradle"
    re = /versionCode\s+(\d+)/
    re2 = /versionName\s+"([\w.]+)"/

    s = File.read(path)
    versionCode = s[re, 1].to_i
    versionName = s[re2, 1]
    version = versionName + "(#{versionCode})"

    sh("curl -X POST 'https://api.telegram.org/bot#{ENV["TELEGRAM_TOKEN"]}/sendMessage' -d 'chat_id=#{ENV["TELEGRAM_CHAT_ID"]}&text=🔥 New version #{version}\nInstallation link .apk \n#{result_url}'")
  end
end
