on:
  pull_request:

name: Test

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm packages
        run: yarn install
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build android
        run: |
          fastlane android build
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: |
            build/app/outputs/apk/release/*.apk
            