on:
  pull_request:

name: Test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm packages
        run: yarn install
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build android
        run: |
          fastlane android build
      - name: Upload build to Diawi
        run: |
          fastlane android upload_build_to_diawi
            